### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by morewings** [adam-cyclones/reactive-css-properties#18]
How to set property into specific HTML Element scope?

**Comment by adam-cyclones** [comment]
@morewings I am sorry I have been away! 

It should be detailed here:
https://github.com/adam-cyclones/reactive-css-properties#recssprops-constructor-details

Where element is `document.querySelector('#my-el')`

Sorry for the really long response time!

**Comment by adam-cyclones** [comment]
No response so I assume the issue has been closed due to a long response time. Sorry!

**Comment by morewings** [comment]
@adam-cyclones no worries. I’ve already made my own package https://github.com/morewings/css-vars-hook
